export const UPDATE_TASK_LOGS = "UPDATE_TASK_LOGS";
export const PROCESS_NOTIFICATION_FROM_SERVER = "PROCESS_NOTIFICATION_FROM_SERVER";
export const UPDATE_TASK_LOG_ENTRY = "UPDATE_TASK_LOG_ENTRY";
export const DELETE_TASK_LOG_ENTRY = "DELETE_TASK_LOG_ENTRY";
